### ISSUE TITLE
Call back issue on facebook connect

### ISSUE THREAD

**Issue by tlacan** [facebook/facebook-swift-sdk#274]
Hello,
I have configured facebook connect on an app. 
We have issues on some devices and account where the call back after login does not work.

The first video shows a device where it works (ios 12)

![success_video](https://user-images.githubusercontent.com/7414060/46464272-3ddac680-c7c6-11e8-9dcb-f0f30cde6d08.gif)

The second video shows the issue where the call back doesn't work (ios 11.4.1)

![fail_video](https://user-images.githubusercontent.com/7414060/46464280-44693e00-c7c6-11e8-86a0-a3948ebd6ea4.gif)

The same build are used and the pod is on commit 581e2398b2c7ffc5d6be3c24da282fa2b83bcb97

**Comment by hordurhauks** [comment]
I might have a related issue. In the callback from LoginManager().login I'm using the newly gathered facebook authenticationToken to make a request to my own server. Every other request fails with error code 53 (software caused connection abort). I think the reason is that the callback is called too early so iOS12 doesn't allow the request. To temporarily fix it I put a little delay before calling my server with the fb auth token. It's a disgusting trick but it does seem to work.

**Comment by codytwinton** [comment]
Version `0.6.0` was just released for Carthage and Cocoapods with support for Xcode 10.2 and Swift 5.0.

Please upgrade to the latest version and let us know if this resolves your issues.
