### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value on login success

### ISSUE THREAD

**Issue by freedoom1984** [facebook/facebook-swift-sdk#314]
Hi,
the flow is this:
- the user try the login with facebook
- the server API go in error
- the user re-try te login with facebook
- the SDK return the error Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

## Environment

- Xcode Version: 10.1
- Swift Version: 4
- Installation Platform & Verison: CocoaPods

<img width="779" alt="schermata 2019-01-04 alle 16 23 17" src="https://user-images.githubusercontent.com/223940/50695842-2669de80-103e-11e9-9c28-4560302f5e54.png">

**Comment by robtimp** [comment]
@freedoom1984 I believe this is crashing because the initializer you are using is internal to the SDK. If you’re using the LoginManager class (not FBSDKLoginManager), you should receive a result that has a `token` property with the AccessToken type, without any need to create one from the FBSDKToken.
