### ISSUE TITLE
Use of unresolved identifier 'LoginManager'

### ISSUE THREAD

**Issue by luciano88** [facebook/facebook-swift-sdk#458]
After updating FacebookLogin pod, XCode can't find LoginManager. How can I fix it without downgrading or importing directly FBSDKLoginKit?

**Comment by angelinec** [comment]
I'm having the same problem too. Updated today from 0.5.0 to 0.7.0 I've imported FacebookCore and FacebookLogin into the file.

Swift **5.0**
Xcode - **10.2.1**
FacebookCore - **0.7.0**
FacebookLogin - **0.7.0**

![Screenshot 2019-05-24 at 5 51 01 PM](https://user-images.githubusercontent.com/9972417/58320140-98a45980-7e4d-11e9-8570-a12be0e2164b.png)

**Comment by sarbogast** [comment]
And it's not the only one. I have the same error about GraphRequestProtocol, GraphAPIVersion, AccessToken, GraphResponseProtocol... In fact pretty much all of the Facebook classes I'm using seem to have disappeared from dependencies.

**Comment by kayoslab** [comment]
To temporarily fix this issue you can import `FBSDKLoginKit` and do `lazy var loginManager = FBSDKLoginKit.LoginManager()` instead. The `AccessToken` interface also changed a bit, so you might want to adapt your code there as well.

**Comment by sarbogast** [comment]
And what about all the other types that are not seen, like GraphRequestProtocol, GraphResponseProtocol and so on. Basically, I have a project that works very well with the SDK in version 0.5, but doesn't build at all with version 0.7. And I integrate the SDK with CocoaPods.

**Comment by angelinec** [comment]
@kayoslab @sarbogast I've downgraded to version 0.5. Going to wait for an update with the proper fixes.

**Comment by sarbogast** [comment]
@angelinec Yep, I guess I will have to do that too.

**Comment by Dfmarulanda** [comment]
I had to downgrade too, 4 weeks ago.

**Comment by bunnyhero** [comment]
Managed to get `LoginManager` to work by importing _both_ FacebookLogin and FBSDKLoginKit:

```swift
import FBSDKLoginKit
import FacebookLogin
```

This also lets me use `AccessToken` as before.

`GraphRequestProtocol` et al are definitely completely missing, though :(

**Comment by peihsendoyle** [comment]
Did you use any CI to build before pushing anything to the production Facebook? Many files missing after upgraded. So shame!

**Comment by caglarcakar** [comment]
At the latest version (0.7.0):
- SDKApplicationDelegate is named as ApplicationDelegate
- userId is named as userID and it is not optional now. 

and also if you are here because of the "Use of unresolved identifier 'LoginManager' error", the answer is from @bunnyhero just import the FBSDKLoginKit

**Comment by bernikovich** [comment]
> At the latest version (0.7.0):
> 
> * SDKApplicationDelegate is named as ApplicationDelegate
> * userId is named as userID and it is not optional now.
> 
> and also if you are here because of the "Use of unresolved identifier 'LoginManager' error", the answer is from @bunnyhero just import the FBSDKLoginKit

What about `AppEventsLogger`?

**Comment by bishalg** [comment]
Any one able to solve the - GraphRequestProtocol issue ? 
still getting - Use of undeclared type 'GraphRequestProtocol'

**Comment by gbhall** [comment]
This is ridiculous.

`Use of undeclared type 'GraphRequestProtocol'`

**Comment by bishalg** [comment]
the situation with Facebook version management is so bad on Core FB SDK ... you can't even trust native Login SDK, how do people trust ReactNative for production app is out of my mind!

**Comment by Pikorua** [comment]
> And what about all the other types that are not seen, like GraphRequestProtocol, GraphResponseProtocol and so on. Basically, I have a project that works very well with the SDK in version 0.5, but doesn't build at all with version 0.7. And I integrate the SDK with CocoaPods.


Facebook changed quite a lot in the latest code but here is the code I came up with that works...

```
let myGraphRequest = GraphRequest(graphPath: "/me", parameters: ["fields": "id, name, first_name, last_name, email, birthday, age_range, picture.width(400), gender"], tokenString: AccessToken.current?.tokenString, version: Settings.defaultGraphAPIVersion, httpMethod: .get)
 
let connection = GraphRequestConnection()
connection.add(myGraphRequest, completionHandler: { (connection, values, error) in
        if let values = values as? [String:Any] { 
                //add your custom code here...
        }
})
```

The response is no longer needed, the JSON response is automatically converted into a dictionary

**Comment by Dfmarulanda** [comment]
Any fix? They have this major bug for 3 months.

**Comment by levibostian** [comment]
@Dfmarulanda I went back to 0.6.0 to solve the issue. 0.7.0 does not seem to even be functional to use.

**Comment by adarhef** [comment]
Same issue here. Pretty much no Facebook symbol can be resolved in my code, and it doesn't seem like the Swift API really changed at all.

**Comment by Pikorua** [comment]
> Same issue here. Pretty much no Facebook symbol can be resolved in my code, and it doesn't seem like the Swift API really changed at all.

A lot of the symbols have been renamed and the old symbols are no longer available. 

If you look at my code example above, you see an example of working code. 

I'm running the latest SDK's in my apps and just made minor adjustments based on the new naming and it's working great!

**Comment by adarhef** [comment]
> > Same issue here. Pretty much no Facebook symbol can be resolved in my code, and it doesn't seem like the Swift API really changed at all.
> 
> A lot of the symbols have been renamed and the old symbols are no longer available.
> 
> If you look at my code example above, you see an example of working code.
> 
> I'm running the latest SDK's in my apps and just made minor adjustments based on the new naming and it's working great!

Thing is I looked at the symbols in the framework itself, and they don't seem to have changed. Like the OP, LoginManager can't be resolved, and it still seems to be of the same name in the framework.

**Comment by Pikorua** [comment]
> Thing is I looked at the symbols in the framework itself, and they don't seem to have changed. Like the OP, LoginManager can't be resolved, and it still seems to be of the same name in the framework.

I see, well I did not look into that but specifically regarding the GraphRequestProtocol and GraphResponseProtocol, there's been changes made. The GraphResponseProtocol is no longer needed since the new SDK already is parsing everything automatically and the GraphRequestProtocol has been changed to GraphRequest which is a subclass from NSObject...
And as far as I'm concerned I did not have any trouble at all with "LoginManager" or AccessToken after updating...

**Comment by joesus** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by bunnyhero** [comment]
step 1: completely break backwards compatibility
step 2: when people notice, close ticket

**Comment by adarhef** [comment]
> We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

I'm pretty sure everyone else here is having the same "use case": we're just importing the library and referencing its symbols to do stuff. It's been impossible for me to update for months. I'm getting warnings from Facebook about my Graph API usage that things might break in a couple of weeks, which adds another layer of urgency.
Honestly at this point I'd probably just switch back to the Objective-C pod if it didn't require rewriting a whole bunch of code.
I'm really sorry for my entitled tone, I don't mean it. It's just disappointing and surprising to me, and if I'm honest it's just not a good look.

**Comment by mksingh143** [comment]
Same issue here and I have resolved by import two classes

Note: 
import FBSDKCoreKit
import FBSDKLoginKit

**Comment by adarhef** [comment]
> Same issue here and I have resolved by import two classes
> 
> Note:
> import FBSDKCoreKit
> import FBSDKLoginKit

You're not supposed to do that, they're an indirect dependency of FacebookCore and FacebookLogin. In principle on your next pod update these can be removed, and their API's are different anyway.

**Comment by astjohn** [comment]
@joesus - If you're going to close the issue, the very least your team could do is adjust the documentation and update the changelog.

For example, in addition to the problems stated above, the following official documentation: 

https://developers.facebook.com/docs/swift/getting-started
=> Still references things like:

```
import FacebookCore

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
  SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
  return true
}

func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
  return SDKApplicationDelegate.shared.application(app, open: url, options: options)
}
```
Which I now understand is wrong due to the recent changes. 

Please update your docs and changelog before making breaking changes like this. It will avoid a lot of frustration from your end-users and is generally considered a best practice.

**Comment by Dfmarulanda** [comment]
It's unrespectful with the community to close the issue without solving it. It is expected from a small company or developer maintaining a little library. But you're Facebook.

**Comment by levibostian** [comment]
I feel for the frustration the users of this repository has felt recently for issues like this one (along with [many](https://github.com/facebook/facebook-swift-sdk/issues/439), [many](https://github.com/facebook/facebook-swift-sdk/issues/433), [many](https://github.com/baumblatt/capacitor-firebase-auth/issues/12) similar issues). 

If it helps anyone who needs to update to version 0.7.0 or 0.8.0, I used [this commit](https://github.com/facebook/facebook-swift-sdk/commit/335ad2c0dd0d277759046a1e4b0d87643ca176e1) where someone fixed the included sample app to compile with all of these frustrating changes. Use your browser's search to search for the unresolved symbol you are experiencing and view the diff for what was done to fix the issue.

Now, please, Facebook. Help us out a little. I believe that I speak for all of us when I say...

Creating releases with broken changes (1) without any documentation to upgrade, (2) no updates to the official Facebook website's documentation with these changes, (3) no deprecated warnings in the source, and (4) leaving us figuring out hacks like 2 import statements `import FacebookLogin` and `import FBLoginKit` (as an example) to get our code to work when this seems like a hack but we are not getting feedback if this is correct or not. I am going to assume that we are not alone with these frustrations now that I see [a commit fixing the sample app](https://github.com/facebook/facebook-swift-sdk/commit/335ad2c0dd0d277759046a1e4b0d87643ca176e1) with the changes done that we all have been sharing with each other without feedback. 

I have not personally experienced this sort of frustration from another open source project before and it confuses me how this is Facebook and it's still happening. We are only human and we all make mistakes I understand. However, I decided I wanted to say something because [these issues continue to happen](https://github.com/baumblatt/capacitor-firebase-auth/issues/12) and we are simply looking for some transparency. If we are the only ones experiencing these issues, we would like to hear that, for example. Viewing a [commit diff](https://github.com/facebook/facebook-swift-sdk/commit/335ad2c0dd0d277759046a1e4b0d87643ca176e1) to fix my app is not ideal if you ask me. 

Thank you for your time.

**Comment by sandeepbol** [comment]
You get an alert on your facebook developer page that you should update -

> For iOS: Please upgrade to the latest SDK version to access new privacy features.

Now, who can deny you guys? You can change policy for public permissions and make people go review their app at your will without giving consideration that many live apps will get affected because of that. And when people want to remain up to date, they only find missing symbols. 

It's just Login with facebook and basic public profile fetching. Is it too much to ask from a small team also that it should work out of the box? Such a shame!

**Comment by bunnyhero** [comment]
To anyone following this issue and not others: this roadmap was posted a few days ago: https://github.com/facebook/facebook-swift-sdk/blob/master/ROADMAP.md

The "for Swift Developers" section of the FAQ is hilariously inaccurate though.

**Comment by carlosdamiao** [comment]
So due to UIWebViewKit being deprecated, I've had to update from 0.5.0 to 0.8.0 and I'm also facing the braking changes.
Although unlike many of others, using FBSDKLoginKit, doesn't solve the AccessToken issue.

**Comment by levibostian** [comment]
@carlosdamiao 0.9.0 is out now. Try that. Also, see [this issue](https://github.com/facebook/facebook-objc-sdk/issues/1035) from facebook about how the UIWebViewKit issue is resolved by them.

**Comment by carlosdamiao** [comment]
@levibostian I meant to say 0.9.0, and it does in fact solve the UIWebViewKit issue. But it brings new issues due to backwards incompatibility, as per detailed in this ticket.

**Comment by 716Buffalo** [comment]
Did this Facebook SDK issue ever get resolved because I get the below "red alert" crash when I try to use my app in the simulator.  I don't know if this is a Login Manager bug or another. I updated all my pods and been switching from FBSDKLoginKit  to Facebook Login....Any help is appreciated! 

 self = [super init];
  if (self) {
    self.authType = FBSDKLoginAuthTypeRerequest;
        NSString *keyChainServiceIdentifier = [NSString stringWithFormat:@"com.facebook.sdk.loginmanager.%@", [NSBundle mainBundle].bundleIdentifier];
    _keychainStore = [[FBSDKKeychainStore alloc] initWithService:keyChainServiceIdentifier accessGroup:nil];
  }
